package cn.freeteam.cms.model;

import java.io.Serializable;

import freemarker.template.TemplateModel;

public class Channel implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.id
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private String id;
    private String hasChildren;
    private String haveChannelRole;
    public static String STATE_EFFECTIVE="1";
    public static String STATE_INVALID="0";
    private String navigation;
    public static String NAVIGATION_YES="1";
    public static String NAVIGATION_NO="0";
    private String pagemark;
    private String htmlchannel;
    private String htmlchannelold;
    private String htmlparchannel;
    private String htmlsite;
    private int indexnum;
    private int maxpage;
    private String folder;//静态页面目录

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.name
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.templet
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private String templet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.contentTemplet
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private String contenttemplet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.img
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.parId
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private String parid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.site
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.url
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private String url;
    private String pageurl;
    private String sitepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.state
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.orderNum
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private Integer ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.clickNum
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private Integer clicknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.description
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.id
     *
     * @return the value of channel.id
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.id
     *
     * @param id the value for channel.id
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.name
     *
     * @return the value of channel.name
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.name
     *
     * @param name the value for channel.name
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.templet
     *
     * @return the value of channel.templet
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public String getTemplet() {
        return templet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.templet
     *
     * @param templet the value for channel.templet
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setTemplet(String templet) {
        this.templet = templet == null ? null : templet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.contentTemplet
     *
     * @return the value of channel.contentTemplet
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public String getContenttemplet() {
        return contenttemplet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.contentTemplet
     *
     * @param contenttemplet the value for channel.contentTemplet
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setContenttemplet(String contenttemplet) {
        this.contenttemplet = contenttemplet == null ? null : contenttemplet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.img
     *
     * @return the value of channel.img
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.img
     *
     * @param img the value for channel.img
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.parId
     *
     * @return the value of channel.parId
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public String getParid() {
        return parid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.parId
     *
     * @param parid the value for channel.parId
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setParid(String parid) {
        this.parid = parid == null ? null : parid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.site
     *
     * @return the value of channel.site
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.site
     *
     * @param site the value for channel.site
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.url
     *
     * @return the value of channel.url
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.url
     *
     * @param url the value for channel.url
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.state
     *
     * @return the value of channel.state
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.state
     *
     * @param state the value for channel.state
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.orderNum
     *
     * @return the value of channel.orderNum
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.orderNum
     *
     * @param ordernum the value for channel.orderNum
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.clickNum
     *
     * @return the value of channel.clickNum
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public Integer getClicknum() {
        return clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.clickNum
     *
     * @param clicknum the value for channel.clickNum
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setClicknum(Integer clicknum) {
        this.clicknum = clicknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.description
     *
     * @return the value of channel.description
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.description
     *
     * @param description the value for channel.description
     *
     * @mbggenerated Mon Jan 23 20:25:00 CST 2012
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }


	public String getHasChildren() {
		return hasChildren;
	}

	public void setHasChildren(String hasChildren) {
		this.hasChildren = hasChildren;
	}

	public String getNavigation() {
		return navigation;
	}

	public void setNavigation(String navigation) {
		this.navigation = navigation;
	}

	public String getPagemark() {
		return pagemark;
	}

	public void setPagemark(String pagemark) {
		this.pagemark = pagemark;
	}

	public String getPageurl() {
		if (url!=null && url.trim().length()>0) {
			pageurl=url;
		}else {
			pageurl=(sitepath!=null?sitepath:"")+getFolder()+"/index.html";
		}
		return pageurl;
	}

	public void setPageurl(String pageurl) {
		this.pageurl = pageurl;
	}

	public String getSitepath() {
		return sitepath;
	}

	public void setSitepath(String sitepath) {
		this.sitepath = sitepath;
	}

	public String getHaveChannelRole() {
		return haveChannelRole;
	}

	public void setHaveChannelRole(String haveChannelRole) {
		this.haveChannelRole = haveChannelRole;
	}

	public String getHtmlchannel() {
		return htmlchannel;
	}

	public void setHtmlchannel(String htmlchannel) {
		this.htmlchannel = htmlchannel;
	}

	public String getHtmlparchannel() {
		return htmlparchannel;
	}

	public void setHtmlparchannel(String htmlparchannel) {
		this.htmlparchannel = htmlparchannel;
	}

	public String getHtmlsite() {
		return htmlsite;
	}

	public void setHtmlsite(String htmlsite) {
		this.htmlsite = htmlsite;
	}

	public String getHtmlchannelold() {
		return htmlchannelold;
	}

	public void setHtmlchannelold(String htmlchannelold) {
		this.htmlchannelold = htmlchannelold;
	}

	public int getIndexnum() {
		return indexnum;
	}

	public void setIndexnum(int indexnum) {
		this.indexnum = indexnum;
	}

	public String getFolder() {
		if (pagemark!=null && pagemark.trim().length()>0) {
			folder=pagemark;
		}else if (indexnum>0) {
			folder=String.valueOf(indexnum);
		}else {
			folder=id;
		}
		return folder;
	}

	public void setFolder(String folder) {
		this.folder = folder;
	}

	public int getMaxpage() {
		return maxpage;
	}

	public void setMaxpage(int maxpage) {
		this.maxpage = maxpage;
	}
}