package cn.freeteam.cms.model;

import java.io.Serializable;
import java.util.Date;

public class InfoSign implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_info_sign.id
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    private String id;
    private String loginname;
    private String name;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_info_sign.userid
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_info_sign.infoid
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    private String infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_info_sign.signtime
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    private Date signtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_info_sign.ip
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_info_sign.id
     *
     * @return the value of freecms_info_sign.id
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_info_sign.id
     *
     * @param id the value for freecms_info_sign.id
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_info_sign.userid
     *
     * @return the value of freecms_info_sign.userid
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_info_sign.userid
     *
     * @param userid the value for freecms_info_sign.userid
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_info_sign.infoid
     *
     * @return the value of freecms_info_sign.infoid
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    public String getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_info_sign.infoid
     *
     * @param infoid the value for freecms_info_sign.infoid
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    public void setInfoid(String infoid) {
        this.infoid = infoid == null ? null : infoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_info_sign.signtime
     *
     * @return the value of freecms_info_sign.signtime
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    public Date getSigntime() {
        return signtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_info_sign.signtime
     *
     * @param signtime the value for freecms_info_sign.signtime
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    public void setSigntime(Date signtime) {
        this.signtime = signtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_info_sign.ip
     *
     * @return the value of freecms_info_sign.ip
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_info_sign.ip
     *
     * @param ip the value for freecms_info_sign.ip
     *
     * @mbggenerated Tue Jan 15 19:08:26 CST 2013
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

	public String getLoginname() {
		return loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}