package cn.freeteam.cms.model;

import java.text.SimpleDateFormat;
import java.util.Date;

import freemarker.template.SimpleDate;

public class Visit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.id
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    private String id;
    private String sitename;
    private String channelname;
    private String infoname;
    private Integer countnum;
    private Date starttime;
    private Date endtime;
    private String starttimeStr;
    private String endtimeStr;
    private SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    private String statType;
    private String datename;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.siteid
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    private String siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.channelid
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    private String channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.infoid
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    private String infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.url
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.addtime
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column freecms_visit.ip
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.id
     *
     * @return the value of freecms_visit.id
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.id
     *
     * @param id the value for freecms_visit.id
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.siteid
     *
     * @return the value of freecms_visit.siteid
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public String getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.siteid
     *
     * @param siteid the value for freecms_visit.siteid
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public void setSiteid(String siteid) {
        this.siteid = siteid == null ? null : siteid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.channelid
     *
     * @return the value of freecms_visit.channelid
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.channelid
     *
     * @param channelid the value for freecms_visit.channelid
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid == null ? null : channelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.infoid
     *
     * @return the value of freecms_visit.infoid
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public String getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.infoid
     *
     * @param infoid the value for freecms_visit.infoid
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public void setInfoid(String infoid) {
        this.infoid = infoid == null ? null : infoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.url
     *
     * @return the value of freecms_visit.url
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.url
     *
     * @param url the value for freecms_visit.url
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.addtime
     *
     * @return the value of freecms_visit.addtime
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.addtime
     *
     * @param addtime the value for freecms_visit.addtime
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column freecms_visit.ip
     *
     * @return the value of freecms_visit.ip
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column freecms_visit.ip
     *
     * @param ip the value for freecms_visit.ip
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

	public String getSitename() {
		return sitename;
	}

	public void setSitename(String sitename) {
		this.sitename = sitename;
	}

	public String getChannelname() {
		return channelname;
	}

	public void setChannelname(String channelname) {
		this.channelname = channelname;
	}

	public String getInfoname() {
		return infoname;
	}

	public void setInfoname(String infoname) {
		this.infoname = infoname;
	}

	public Integer getCountnum() {
		return countnum;
	}

	public void setCountnum(Integer countnum) {
		this.countnum = countnum;
	}

	public Date getStarttime() {
		return starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getStarttimeStr() {
		if (starttime!=null) {
			starttimeStr=sdf.format(starttime);
		}
		return starttimeStr;
	}

	public void setStarttimeStr(String starttimeStr) {
		this.starttimeStr = starttimeStr;
	}

	public String getEndtimeStr() {
		if (endtime!=null) {
			endtimeStr=sdf.format(endtime);
		}
		return endtimeStr;
	}

	public void setEndtimeStr(String endtimeStr) {
		this.endtimeStr = endtimeStr;
	}

	public String getStatType() {
		return statType;
	}

	public void setStatType(String statType) {
		this.statType = statType;
	}

	public String getDatename() {
		return datename;
	}

	public void setDatename(String datename) {
		this.datename = datename;
	}
}