package cn.freeteam.model;

import java.io.Serializable;

public class Roles implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.id
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    private String id;
    private String adduser;
    private boolean haveUserRole;
    //此角色是否给一个用户授权
    private boolean haveRoleUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.name
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.isOk
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    private String isok;
    private String isokStr;
	public String getIsokStr() {
		isokStr="否";
		if ("1".equals(isok)) {
			isokStr="是";
		}
		return isokStr;
	}

	public void setIsokStr(String isokStr) {
		this.isokStr = isokStr;
	}


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.id
     *
     * @return the value of roles.id
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.id
     *
     * @param id the value for roles.id
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.name
     *
     * @return the value of roles.name
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.name
     *
     * @param name the value for roles.name
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.isOk
     *
     * @return the value of roles.isOk
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    public String getIsok() {
        return isok;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.isOk
     *
     * @param isok the value for roles.isOk
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    public void setIsok(String isok) {
        this.isok = isok == null ? null : isok.trim();
    }

	public String getAdduser() {
		return adduser;
	}

	public void setAdduser(String adduser) {
		this.adduser = adduser;
	}

	public boolean getHaveUserRole() {
		return haveUserRole;
	}

	public void setHaveUserRole(boolean haveUserRole) {
		this.haveUserRole = haveUserRole;
	}
	public boolean getHaveRoleUser() {
		return haveRoleUser;
	}

	public void setHaveRoleUser(boolean haveRoleUser) {
		this.haveRoleUser = haveRoleUser;
	}
}