package cn.freeteam.dao;


import java.util.List;
import org.apache.ibatis.annotations.Param;

import cn.freeteam.model.Operlogs;
import cn.freeteam.model.OperlogsExample;

public interface OperlogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operLogs
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    int countByExample(OperlogsExample example);
    List<Operlogs> selectPageByExample(OperlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operLogs
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    int deleteByExample(OperlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operLogs
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operLogs
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    int insert(Operlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operLogs
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    int insertSelective(Operlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operLogs
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    List<Operlogs> selectByExample(OperlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operLogs
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    Operlogs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operLogs
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    int updateByExampleSelective(@Param("record") Operlogs record, @Param("example") OperlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operLogs
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    int updateByExample(@Param("record") Operlogs record, @Param("example") OperlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operLogs
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    int updateByPrimaryKeySelective(Operlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operLogs
     *
     * @mbggenerated Fri Dec 16 16:07:41 CST 2011
     */
    int updateByPrimaryKey(Operlogs record);
}