package cn.freeteam.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import cn.freeteam.model.Unit;
import cn.freeteam.model.UnitExample;


public interface UnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2011
     */
    int countByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2011
     */
    int deleteByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2011
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2011
     */
    int insert(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2011
     */
    int insertSelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2011
     */
    List<Unit> selectByExample(UnitExample example);
    List<Unit> selectByExampleCache(UnitExample example);
    List<Unit> findByUser(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2011
     */
    Unit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2011
     */
    int updateByExampleSelective(@Param("record") Unit record, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2011
     */
    int updateByExample(@Param("record") Unit record, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2011
     */
    int updateByPrimaryKeySelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Mar 01 20:39:43 CST 2011
     */
    int updateByPrimaryKey(Unit record);
    
    public List<Unit> selectUnit(@Param("parid")String parid);
    public List<Unit> selectUnitByparid(@Param("parid")String parid);
    public void updatePar(Unit unit);
}