package cn.freeteam.cms.dao;

import cn.freeteam.cms.model.Applyopen;
import cn.freeteam.cms.model.ApplyopenExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplyopenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_applyopen
     *
     * @mbggenerated Wed Mar 20 16:49:42 CST 2013
     */
    int countByExample(ApplyopenExample example);
    int countByExampleCache(ApplyopenExample example);
    List<Applyopen> selectPageByExample(ApplyopenExample example);
    List<Applyopen> selectPageByExampleCache(ApplyopenExample example);
    Applyopen selectByQuerycode(String querycode);
    Applyopen selectByQuerycodeCache(String querycode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_applyopen
     *
     * @mbggenerated Wed Mar 20 16:49:42 CST 2013
     */
    int deleteByExample(ApplyopenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_applyopen
     *
     * @mbggenerated Wed Mar 20 16:49:42 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_applyopen
     *
     * @mbggenerated Wed Mar 20 16:49:42 CST 2013
     */
    int insert(Applyopen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_applyopen
     *
     * @mbggenerated Wed Mar 20 16:49:42 CST 2013
     */
    int insertSelective(Applyopen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_applyopen
     *
     * @mbggenerated Wed Mar 20 16:49:42 CST 2013
     */
    List<Applyopen> selectByExample(ApplyopenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_applyopen
     *
     * @mbggenerated Wed Mar 20 16:49:42 CST 2013
     */
    Applyopen selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_applyopen
     *
     * @mbggenerated Wed Mar 20 16:49:42 CST 2013
     */
    int updateByExampleSelective(@Param("record") Applyopen record, @Param("example") ApplyopenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_applyopen
     *
     * @mbggenerated Wed Mar 20 16:49:42 CST 2013
     */
    int updateByExample(@Param("record") Applyopen record, @Param("example") ApplyopenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_applyopen
     *
     * @mbggenerated Wed Mar 20 16:49:42 CST 2013
     */
    int updateByPrimaryKeySelective(Applyopen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_applyopen
     *
     * @mbggenerated Wed Mar 20 16:49:42 CST 2013
     */
    int updateByPrimaryKey(Applyopen record);
}