package cn.freeteam.cms.dao;

import cn.freeteam.cms.model.Memberauth;
import cn.freeteam.cms.model.MemberauthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberauthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_memberAuth
     *
     * @mbggenerated Wed Jan 30 18:59:19 CST 2013
     */
    int countByExample(MemberauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_memberAuth
     *
     * @mbggenerated Wed Jan 30 18:59:19 CST 2013
     */
    int deleteByExample(MemberauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_memberAuth
     *
     * @mbggenerated Wed Jan 30 18:59:19 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_memberAuth
     *
     * @mbggenerated Wed Jan 30 18:59:19 CST 2013
     */
    int insert(Memberauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_memberAuth
     *
     * @mbggenerated Wed Jan 30 18:59:19 CST 2013
     */
    int insertSelective(Memberauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_memberAuth
     *
     * @mbggenerated Wed Jan 30 18:59:19 CST 2013
     */
    List<Memberauth> selectByExample(MemberauthExample example);
    List<Memberauth> selectPageByExample(MemberauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_memberAuth
     *
     * @mbggenerated Wed Jan 30 18:59:19 CST 2013
     */
    Memberauth selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_memberAuth
     *
     * @mbggenerated Wed Jan 30 18:59:19 CST 2013
     */
    int updateByExampleSelective(@Param("record") Memberauth record, @Param("example") MemberauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_memberAuth
     *
     * @mbggenerated Wed Jan 30 18:59:19 CST 2013
     */
    int updateByExample(@Param("record") Memberauth record, @Param("example") MemberauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_memberAuth
     *
     * @mbggenerated Wed Jan 30 18:59:19 CST 2013
     */
    int updateByPrimaryKeySelective(Memberauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_memberAuth
     *
     * @mbggenerated Wed Jan 30 18:59:19 CST 2013
     */
    int updateByPrimaryKey(Memberauth record);
}