package cn.freeteam.cms.dao;

import cn.freeteam.cms.model.MembergroupAuth;
import cn.freeteam.cms.model.MembergroupAuthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MembergroupAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_auth
     *
     * @mbggenerated Fri Feb 01 15:56:45 CST 2013
     */
    int countByExample(MembergroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_auth
     *
     * @mbggenerated Fri Feb 01 15:56:45 CST 2013
     */
    int deleteByExample(MembergroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_auth
     *
     * @mbggenerated Fri Feb 01 15:56:45 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_auth
     *
     * @mbggenerated Fri Feb 01 15:56:45 CST 2013
     */
    int insert(MembergroupAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_auth
     *
     * @mbggenerated Fri Feb 01 15:56:45 CST 2013
     */
    int insertSelective(MembergroupAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_auth
     *
     * @mbggenerated Fri Feb 01 15:56:45 CST 2013
     */
    List<MembergroupAuth> selectByExample(MembergroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_auth
     *
     * @mbggenerated Fri Feb 01 15:56:45 CST 2013
     */
    MembergroupAuth selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_auth
     *
     * @mbggenerated Fri Feb 01 15:56:45 CST 2013
     */
    int updateByExampleSelective(@Param("record") MembergroupAuth record, @Param("example") MembergroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_auth
     *
     * @mbggenerated Fri Feb 01 15:56:45 CST 2013
     */
    int updateByExample(@Param("record") MembergroupAuth record, @Param("example") MembergroupAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_auth
     *
     * @mbggenerated Fri Feb 01 15:56:45 CST 2013
     */
    int updateByPrimaryKeySelective(MembergroupAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_membergroup_auth
     *
     * @mbggenerated Fri Feb 01 15:56:45 CST 2013
     */
    int updateByPrimaryKey(MembergroupAuth record);
}