package cn.freeteam.cms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import cn.freeteam.cms.model.RoleSite;
import cn.freeteam.cms.model.RoleSiteExample;

public interface RoleSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_role_site
     *
     * @mbggenerated Tue Oct 16 21:25:57 CST 2012
     */
    int countByExample(RoleSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_role_site
     *
     * @mbggenerated Tue Oct 16 21:25:57 CST 2012
     */
    int deleteByExample(RoleSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_role_site
     *
     * @mbggenerated Tue Oct 16 21:25:57 CST 2012
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_role_site
     *
     * @mbggenerated Tue Oct 16 21:25:57 CST 2012
     */
    int insert(RoleSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_role_site
     *
     * @mbggenerated Tue Oct 16 21:25:57 CST 2012
     */
    int insertSelective(RoleSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_role_site
     *
     * @mbggenerated Tue Oct 16 21:25:57 CST 2012
     */
    List<RoleSite> selectByExample(RoleSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_role_site
     *
     * @mbggenerated Tue Oct 16 21:25:57 CST 2012
     */
    RoleSite selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_role_site
     *
     * @mbggenerated Tue Oct 16 21:25:57 CST 2012
     */
    int updateByExampleSelective(@Param("record") RoleSite record, @Param("example") RoleSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_role_site
     *
     * @mbggenerated Tue Oct 16 21:25:57 CST 2012
     */
    int updateByExample(@Param("record") RoleSite record, @Param("example") RoleSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_role_site
     *
     * @mbggenerated Tue Oct 16 21:25:57 CST 2012
     */
    int updateByPrimaryKeySelective(RoleSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_role_site
     *
     * @mbggenerated Tue Oct 16 21:25:57 CST 2012
     */
    int updateByPrimaryKey(RoleSite record);
}