package cn.freeteam.cms.dao;

import cn.freeteam.cms.model.Visit;
import cn.freeteam.cms.model.VisitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_visit
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    int countByExample(VisitExample example);
    int countByExampleCache(VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_visit
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    int deleteByExample(VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_visit
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_visit
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    int insert(Visit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_visit
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    int insertSelective(Visit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_visit
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    List<Visit> selectByExample(VisitExample example);
    
    List<Visit> channelVisit(VisitExample example);
    List<Visit> channelVisitPage(VisitExample example);
    int channelVisitCount(VisitExample example);
    int channelVisitSum(VisitExample example);
    
    int siteVisitSum(VisitExample example);
    List<Visit> siteVisit(VisitExample example);
    List<Visit> siteVisitPage(VisitExample example);
    int siteVisitCount(VisitExample example);
    

    List<Visit> infoVisit(VisitExample example);
    List<Visit> infoVisitPage(VisitExample example);
    int infoVisitCount(VisitExample example);
    int infoVisitSum(VisitExample example);
    

    int visitSum(VisitExample example);
    
    List<Visit> visitYear(VisitExample example);
    List<Visit> visitYearPage(VisitExample example);
    int visitYearCount(VisitExample example);
    
    List<Visit> visitMonth(VisitExample example);
    List<Visit> visitMonthPage(VisitExample example);
    int visitMonthCount(VisitExample example);
    
    List<Visit> visitDay(VisitExample example);
    List<Visit> visitDayPage(VisitExample example);
    int visitDayCount(VisitExample example);
    
    List<Visit> visitWeek(VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_visit
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    Visit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_visit
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    int updateByExampleSelective(@Param("record") Visit record, @Param("example") VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_visit
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    int updateByExample(@Param("record") Visit record, @Param("example") VisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_visit
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    int updateByPrimaryKeySelective(Visit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table freecms_visit
     *
     * @mbggenerated Wed May 22 16:50:27 CST 2013
     */
    int updateByPrimaryKey(Visit record);
}